### PR TITLE
Add Free monad

### PR DESCRIPTION
**Pull request by YBogomolov**
A naïve classless port from v1, exposing a pipeable interface.

#### Additional context

Free overall is considered a not-so-good approach performance-wise, so I suggest taking a look at either possibility of implementing Church-encoded Free monads, or using Oleg Kiselyov's Freer monads (http://okmij.org/ftp/Haskell/extensible/more.pdf).

I would like to discuss design decisions for this module, so I can understand all concerns and code a better implementation of Free.

### CODE REVIEW

**Comment by YBogomolov** [comment]
@gcanti Sorry for bothering you, but should I close this PR or somehow improve it in order to get it merged?

**Comment by gcanti** [comment]
> or somehow improve it

@YBogomolov maybe some tests and/or a usage example

**Comment by YBogomolov** [comment]
@gcanti Done. I've added tests (ensuring 100% coverage), and included simple expression tree example as a part of test suite.

**Comment by gcanti** [comment]
Thanks @YBogomolov !

Nitpick: `@since 0.1.2` should be `@since 0.1.3`

**Pull request merged**
