### PR TITLE
feature: Ix{Applicative,Apply,Chain,Functor,Monad,Pointed}

### PR DESCRIPTION
**Pull request by derrickbeining**
Adds type classes for
  - IxApplicative
  - IxApply
  - IxChain
  - IxFunctor
  - IxMonad
  - IxPointed

I didn't have any data types for which to implement the classes so I wasn't really sure if I should write tests. Please advise.

### CODE REVIEW

**Comment by gcanti** [comment]
I would make the type classes `pipe`-ables as in the original PR.

What's the purpose of the `IxFunctor` module? At first sight there's no difference from `Functor`.

Also note that in `fp-ts@3` I'm going to drop some constraints:

- `Chain` extends `Functor`
- `Monad` extends `Chain`, `Pointed`

> I didn't have any data types for which to implement the classes

An actual use case for these new type classes would be helpful

**Comment by derrickbeining** [comment]
> I would make the type classes pipe-ables as in the original PR.

Even though all other type classes for the version of `fp-ts` in the `package.json` are not pipeable? I figured I should keep this stuff consistent with the rest of the type classes that would be used in this version, and we'd update them whenever `fp-ts-contrib` was updated to use a new version of `fp-ts` that has pipeable typeclasses.  I can update them to be pipeable though if you don't think it needs to be consistent.

> What's the purpose of the IxFunctor module? At first sight there's no difference from Functor.

That's a great question. I hadn't thought about that. I'm mostly just cargo-culting what I found in Haskell and PureScript. I suppose it's not materially different except that it doesn't support kinds less than `Type -> Type -> Type -> Type`, although in PS you get a little more polymorphism from poly-kinds, so it doesn't support types of kind less polymorphic than `forall ix. ix -> ix -> Type -> Type`. I can't really think of a way that you might implement `IxFunctor` differently from `Functor` in TS, though, so yeah, idk. I asked Gary Burgess who wrote the `purescript-indexed-monad` library and he doesn't think the `IxFunctor` class is strictly necessary, even in PS. But perhaps for the sake of convention and obviousness, including `IxFunctor` could be beneficial. Happy to defer to your discretion.

> Also note that in fp-ts@3 I'm going to drop some constraints:

Does that mean you think I should drop the constraints here as well? I was thinking I was supposed to just adjust this stuff to fit with the version of `fp-ts` in the `package.json`.

> An actual use case for these new type classes would be helpful

I suppose I'll try to adapt the `IxState` type from the other PR for the dependencies in this repo then.

**Comment by derrickbeining** [comment]
RE: 
> What's the purpose of the IxFunctor module? At first sight there's no difference from Functor.

I asked about IxFunctor in the #purescript channel in the FP slack and Nate Faubion has some reasoning for it, but it may only be applicable to PS and not TS. But perhaps the could give you the info you need to decide whether you'd want to include IxFunctor in addition to Functor 

https://functionalprogramming.slack.com/archives/C04NA444H/p1620249067107800

**Comment by waynevanson** [comment]
Should we change it the prefix from i to ix? imap, for example, is used in the invariant type class, right?

**Comment by waynevanson** [comment]
We will need docs somewhere to explain how to do module augmentation for these, because IxState needs kind3 and kind2.

**Comment by derrickbeining** [comment]
> Should we change it the prefix from i to ix? imap, for example, is used in the invariant type class, right?

Good point.  That hadn't crossed my mind. Seems like the right thing to do.

> We will need docs somewhere to explain how to do module augmentation for these, because IxState needs kind3 and kind2.

Yeah I suppose so. Where would it make sense to put that? Also, it would be good to here @gcanti 's thought about that hack. It's certainly feels hacky to have to register a Kind3 type as Kind2 as a way of enforcing that the index parameters are the same type.

@waynevanson would you be interested in making a PR to my branch to add the `IxState` and `IxStateT` stuff? I feel you might be a bit more familiar with implementing that than I am.

**Comment by derrickbeining** [comment]
Hey y'all, update: I just went ahead and published [fp-ts-indexed-monad](https://www.npmjs.com/package/fp-ts-indexed-monad) as a separate package. Do we want to go ahead and close this PR?

**Pull request closed without merging**
