### PR TITLE
feat: export modules from entrypoint

### LINKED ISSUE #70: import modules directly from library entrypoint
## 🚀 Feature request

The same as https://github.com/gcanti/io-ts-types/issues/129 but for this library.

I removed the extra information for the issue because the issue is self explantory via the issue.

### PR DESCRIPTION
**Pull request by waynevanson**
closes #70 

The modules are exported how they're consumed in `fp-ts`, but I wasn't sure about the functions.
What would you recommend?

Typescript upgraded to `^3.8.3`, as described in detail in the commits.

### CODE REVIEW

**Comment by IMax153** [comment]
Hey @waynevanson - thank you for the PR! If I am understanding correctly, the use case for this change would be to allow importing modules like this

```typescript
import { List } from 'fp-ts-contrib'
```

as opposed to importing modules like this

```typescript
import * as L from 'fp-ts-contrib/lib/List'
```

I think I have two major concerns with this PR before I would consider it ready for merge.

First, do we know what the implications are on tree shakability with this new import syntax? Do you know if bundlers will be able to recognize remove unused code? The current approach that is being taken to improve module import syntax in the `fp-ts` ecosystem is to [run a build script](https://github.com/gcanti/fp-ts/tree/master/scripts) right before release that separates the modules into their own directories, so you can drop the `/lib/` (or `/es6/`) portion and import modules as

```typescript
import * as L from 'fp-ts-contrib/List'
```

This preserves tree shakability of the modules. 

While we try to determine the impact on tree shakability, we could also add these build scripts to `fp-ts-contrib` to allow dropping the `/lib/` (or `/es6/`) portion of the imports which would improve the import ergonomics. Let me know what you think!

Second, the bump in typescript versions constitutes a breaking change (@gcanti correct me if I am wrong). We try to avoid breaking changes as much as possible until we have enough new features for the library to constitute a major release. For many of the `fp-ts` ecosystem libraries, this means that at this point we are waiting on `v3.0.0` of `fp-ts` to be released before we introduce major breaking changes. Any changes in the meantime should be backwards compatible with previous versions of the library.

We could address your request while also maintaining backwards compatibility by adding `import`/`export` statements to the `index.ts` file for all modules, similar to how other `fp-ts` ecosystem libraries roll up their exports. See [here](https://github.com/gcanti/fp-ts/blob/master/src/index.ts) for what I mean. If this is alright with you, I would ask that you update your PR to use this approach for now to avoid any breaking changes!

**Comment by waynevanson** [comment]
Yes, the use case you be out forward is what I intended in the PR.

Tree shaking may not work via Babel. Babel does not understand this unless it has the correct plugin. However, it's stage four in the ECMAScript spec

https://babeljs.io/docs/en/babel-plugin-proposal-export-namespace-from
https://github.com/tc39/proposal-export-ns-from

The example you've given is what I was trying to do, but with sugar. I'll change this for you so we can get it pulled without the breaking changes!

Thank you for being kind.

**Comment by waynevanson** [comment]
How should we expose the helpers: the functions that extend Task or the functions that take typeclasses as a parameter?

I may leave these out and only expose the Modules that are a typeclass for the time being.

**Comment by IMax153** [comment]
> How should we expose the helpers: the functions that extend Task or the functions that take typeclasses as a parameter?

This is a good question.

In the main `fp-ts` repo, the "helpers" in the `function` module are exported under the `function` namespace from `index.ts`. I think we can adopt a similar approach for `fp-ts-contrib` and export the helper functions by file name in the same manner that the type class modules are exported. This may create some weird syntax (i.e. `batchTraverse.batchTraverse`) but it does keep things consistent, and users of the library always have the option of importing the helpers directly.

**Comment by gcanti** [comment]
> the bump in typescript versions constitutes a breaking change (@gcanti correct me if I am wrong)

That's not a breaking change as long as we only use `typescript@3.5` features in the code.

So bumping to `3.8.3` is not a breaking change per se, but using the `export * as ... from ...` syntax (which was [added](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#export--as-ns-syntax) in `typescript@3.8`) is actually a breaking change.

**Comment by waynevanson** [comment]
@IMax153  @gcanti This is ready for review.

**Comment by IMax153** [comment]
Apologies @waynevanson, but could you update your `@since` tags to `0.1.21` in the `index.ts` file? We released a new version of `fp-ts-contrib` since this PR was opened containing some updates to the `List` type class.

**Comment by waynevanson** [comment]
I'll do it in 24 hours, I need some sleep.

**Comment by waynevanson** [comment]
@IMax153 your turn

**Comment by IMax153** [comment]
@waynevanson - LGTM 👍, thank you!
@gcanti - merged!

**Comment by gcanti** [comment]
@waynevanson @IMax153 thank you, released.

**Comment by waynevanson** [comment]
LOVELY! 🤎

**Pull request merged**
