### PR TITLE
Add some combinators to TaskOption

### PR DESCRIPTION
**Pull request by bwlt**

### CODE REVIEW

**Comment by gcanti** [comment]
@giogonzo see `getFilterableComposition`

**Comment by gcanti** [comment]
```ts
export const taskOption: Monad1<URI> & Alt1<URI> & Filterable1<URI> = {
  URI,
  map: T.map,
  of: some,
  ap: T.ap,
  chain: T.chain,
  alt: T.alt,
  ...getFilterableComposition(task, option)
}
```

**Comment by giogonzo** [comment]
ooooh nice, thanks @gcanti 

@bwlt I went ahead and pushed the commit myself 👼 `filter` is exactly the same as before plus we now have a few more combinators "for free"

**Comment by bwlt** [comment]
Thank you for your reviews! looks very good now :)

**Pull request merged**
